import pathlib
p = pathlib.Path('cli/vexor/core/mitm_proxy.py')
c = []
def L(s): c.append(s)
L('# Vexor MITM Proxy v3.0 - Real HTTPS Interception')
L('# Bug Fix 3: Real TLS termination with CA cert')
L('# Bug Fix 4: Match/Replace rules actually applied')
L('# New: Passive scanning, WebSocket, Burp parity')
L('import asyncio, re, time, json, base64, ssl, os, socket, hashlib')
L('from typing import Callable, Optional, List, Dict, Any, Tuple')
L('from dataclasses import dataclass, field')
L('from pathlib import Path')
L('')
L('try:')
L('    from cryptography import x509')
L('    from cryptography.x509.oid import NameOID')
L('    from cryptography.hazmat.primitives import hashes, serialization')
L('    from cryptography.hazmat.primitives.asymmetric import rsa')
L('    from cryptography.hazmat.backends import default_backend')
L('    import datetime as _dt')
L('    HAS_CRYPTO = True')
L('except ImportError:')
L('    HAS_CRYPTO = False')
L('')
L('from vexor.config import HOME_DIR')
L('CA_KEY_FILE  = HOME_DIR / chr(34) + chr(118) + chr(101) + chr(120) + chr(111) + chr(114) + chr(45) + chr(99) + chr(97) + chr(46) + chr(107) + chr(101) + chr(121) + chr(34)')
