"""
Vexor HTML Report Generator
"""
import datetime
from pathlib import Path
from jinja2 import Template
from vexor.config import TOOL_VERSION, TOOL_AUTHOR


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{{ title }}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { background: #0a0a0f; color: #cccccc; font-family: 'Courier New', monospace; }
  .header { background: #0d0d1a; border-bottom: 2px solid #00ffff; padding: 30px; }
  .logo { color: #00ffff; font-size: 24px; font-weight: bold; }
  .subtitle { color: #ff00ff; margin-top: 5px; }
  .meta { color: #888; margin-top: 10px; font-size: 12px; }
  .container { max-width: 1200px; margin: 0 auto; padding: 30px; }
  .summary { display: grid; grid-template-columns: repeat(5, 1fr); gap: 15px; margin: 20px 0; }
  .stat-card { background: #0d0d1a; border: 1px solid #1a1a2e; padding: 20px; text-align: center; border-radius: 4px; }
  .stat-value { font-size: 32px; font-weight: bold; }
  .stat-label { color: #888; font-size: 12px; margin-top: 5px; }
  .critical { color: #ff0000; } .high { color: #ff4400; }
  .medium { color: #ffaa00; } .low { color: #00aaff; } .info { color: #888; }
  table { width: 100%; border-collapse: collapse; margin: 20px 0; }
  th { background: #1a1a2e; color: #00ffff; padding: 12px; text-align: left; }
  td { padding: 10px 12px; border-bottom: 1px solid #1a1a2e; }
  tr:hover { background: #0d0d1a; }
  .section-title { color: #ff00ff; font-size: 18px; margin: 30px 0 10px; border-bottom: 1px solid #1a1a2e; padding-bottom: 10px; }
  .footer { text-align: center; color: #555; padding: 20px; border-top: 1px solid #1a1a2e; margin-top: 40px; }
</style>
</head>
<body>
<div class="header">
  <div class="logo">⬡ VEXOR SECURITY REPORT</div>
  <div class="subtitle">AI-Powered CLI Security Toolkit v{{ version }}</div>
  <div class="meta">
    Target: {{ target }} | Date: {{ date }} | Created by {{ author }}
  </div>
</div>
<div class="container">
  <div class="section-title">◈ EXECUTIVE SUMMARY</div>
  <div class="summary">
    <div class="stat-card"><div class="stat-value" style="color:#cccccc">{{ total }}</div><div class="stat-label">TOTAL FINDINGS</div></div>
    <div class="stat-card"><div class="stat-value critical">{{ critical }}</div><div class="stat-label">CRITICAL</div></div>
    <div class="stat-card"><div class="stat-value high">{{ high }}</div><div class="stat-label">HIGH</div></div>
    <div class="stat-card"><div class="stat-value medium">{{ medium }}</div><div class="stat-label">MEDIUM</div></div>
    <div class="stat-card"><div class="stat-value low">{{ low }}</div><div class="stat-label">LOW</div></div>
  </div>

  <div class="section-title">◈ FINDINGS</div>
  <table>
    <tr>
      <th>Severity</th><th>Module</th><th>Vulnerability</th>
      <th>Endpoint</th><th>Parameter</th><th>Description</th>
    </tr>
    {% for f in findings %}
    <tr>
      <td class="{{ f.severity|lower }}"><strong>{{ f.severity }}</strong></td>
      <td>{{ f.module }}</td>
      <td>{{ f.vuln }}</td>
      <td style="word-break:break-all">{{ f.endpoint }}</td>
      <td>{{ f.param or '-' }}</td>
      <td>{{ f.description }}</td>
    </tr>
    {% endfor %}
    {% if not findings %}
    <tr><td colspan="6" style="text-align:center;color:#00ff88">No vulnerabilities found</td></tr>
    {% endif %}
  </table>

  {% for f in findings %}
  {% if f.severity in ['CRITICAL', 'HIGH'] %}
  <div class="section-title">◈ {{ f.vuln }}</div>
  <table>
    <tr><th>Field</th><th>Value</th></tr>
    <tr><td>Severity</td><td class="{{ f.severity|lower }}">{{ f.severity }}</td></tr>
    <tr><td>Endpoint</td><td>{{ f.endpoint }}</td></tr>
    {% if f.param %}<tr><td>Parameter</td><td>{{ f.param }}</td></tr>{% endif %}
    {% if f.payload %}<tr><td>Payload</td><td><code>{{ f.payload }}</code></td></tr>{% endif %}
    {% if f.evidence %}<tr><td>Evidence</td><td><pre>{{ f.evidence }}</pre></td></tr>{% endif %}
    <tr><td>Description</td><td>{{ f.description }}</td></tr>
    <tr><td>Remediation</td><td>{{ f.remediation }}</td></tr>
    {% if f.ai_note %}<tr><td>AI Analysis</td><td>{{ f.ai_note }}</td></tr>{% endif %}
  </table>
  {% endif %}
  {% endfor %}
</div>
<div class="footer">
  Generated by Vexor v{{ version }} | Created by {{ author }} | {{ date }}
</div>
</body>
</html>"""


class HTMLReport:
    def __init__(self, title: str = "Vexor Security Report"):
        self.title = title

    async def generate(self, output_path: str, findings: list = None, target: str = "") -> str:
        findings = findings or []
        from collections import Counter
        counts = Counter(f.get("severity", "INFO") for f in findings)

        template = Template(HTML_TEMPLATE)
        html = template.render(
            title=self.title,
            version=TOOL_VERSION,
            author=TOOL_AUTHOR,
            target=target or "N/A",
            date=datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            findings=findings,
            total=len(findings),
            critical=counts.get("CRITICAL", 0),
            high=counts.get("HIGH", 0),
            medium=counts.get("MEDIUM", 0),
            low=counts.get("LOW", 0),
        )

        Path(output_path).write_text(html, encoding="utf-8")
        return output_path
